name: Publish

on:
  push:
    branches: ['release/*']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.104.0
        with:
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/variables@v1.104.0
      - uses: taiga-family/ci/actions/setup/node@v1.104.0
      - uses: taiga-family/ci/actions/setup/config/npm@v1.104.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish

      - name: Get new version
        id: info
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
